### ISSUE TITLE
求救：添加集成页面输入完各种信息后显示错误

### ISSUE THREAD

**Issue by easony1989** [MapleEve/lifesmart-for-homeassistant#8]
根据说明生成apptoken等信息，输入后出现
Unknown error occurred
![Snipaste_2024-06-09_14-35-13](https://github.com/MapleEve/lifesmart-for-homeassistant/assets/22462578/7bc25ecf-60b7-4b76-98d7-d118f19ff005)
![Snipaste_2024-06-09_14-32-54](https://github.com/MapleEve/lifesmart-for-homeassistant/assets/22462578/80af482d-2910-4d29-97f3-4b488cf5eb64)
![Snipaste_2024-06-09_14-32-34](https://github.com/MapleEve/lifesmart-for-homeassistant/assets/22462578/15ded4bc-c98e-4578-b522-240a9ea53f40)

查看日志如下
日志记录器: aiohttp.server
来源: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
首次出现: 13:45:42 (36 次总计出现)
上次记录: 14:32:11

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 70, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 414, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 517, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/lifesmart/config_flow.py", line 101, in async_step_user
    await self.async_set_unique_id(validated["unique_id"])
                                   ^^^^^^^^^
UnboundLocalError: cannot access local variable 'validated' where it is not associated with a value

**Comment by johnmacQ** [comment]
我也有同样的问题

**Comment by ideawork1977** [comment]
我也一模一樣，求解！

**Comment by MapleEve** [comment]
我看了一下，你们都 HAAS 版本是多少，有可能是 AIOHTTP 版本不对造成的……

**Comment by easony1989** [comment]
> 我看了一下，你们都 HAAS 版本是多少，有可能是 AIOHTTP 版本不对造成的……

我的 Core 2024.6.1

**Comment by ideawork1977** [comment]
> 我看了一下，你們都 HAAS 版本是多少，有可能是 AIOHTTP 版本不對造成的......

我從6月份開始都持續更新
<img width="586" alt="截圖 2024-07-18 下午5 01 07" src="https://github.com/user-attachments/assets/d199e1c4-ebdd-4546-8230-c2d276fc0ea3">

**Comment by 00make** [comment]
我也有同样的问题

**Comment by snowyang228** [comment]
我也有同样的问题，不知道如何解决。

**Comment by bamankj** [comment]
可有解决方法

**Comment by MapleEve** [comment]
新版本增加了 websocket 的客户端安装应该解决了
